@host = http://127.0.0.1:5001

### TEST CONNECTION
GET {{host}}/test

### Register User
POST {{host}}/api/register
Content-Type: application/json

{
    "display_name": "John Doe",
    "username": "johndoe",
    "email": "john@example.com",
    "password": "123456",
    "confirm_password": "123456"
}

### Login
POST {{host}}/api/login
Content-Type: application/json

{
    "username": "johndoe",
    "password": "123456"
}

### Get Post
GET {{host}}/post/1
Content-Type: application/json

### Get Posts
GET {{host}}/feed/posts
Content-Type: application/json

### Get Trending Posts
GET {{host}}/trending/posts
Content-Type: application/json

### Logout
POST {{host}}/api/logout

### Try after logout
GET {{host}}/api/me 