### ========================================
### AUTHENTICATION TESTS
### ========================================
@host = {{$dotenv HOST}}

### 1. Register User
POST {{host}}/auth/register
Content-Type: application/json

{
    "display_name": "Kent Shien",
    "username": "kent12345",
    "email": "bonzakent16@gmail.com",
    "password": "123456",
    "confirm_password": "123456"
}

### 2. Login (copy access_token to config.http)
POST {{host}}/auth/login
Content-Type: application/json

{
    "username": "kent12345",
    "password": "123456"
}

### 3. Refresh Token
POST {{host}}/auth/refresh

### 4. Logout
POST {{host}}/auth/logout