@host = http://127.0.0.1:5001

### TEST CONNECTION
GET {{host}}/test

### Register User
POST {{host}}/api/register
Content-Type: application/json

{
    "display_name": "John Doe",
    "username": "johndoe",
    "email": "john@example.com",
    "password": "123456",
    "confirm_password": "123456"
}

### Login
POST {{host}}/api/login
Content-Type: application/json

{
    "username": "johndoe",
    "password": "123456"
}

### Get Post
GET {{host}}/post/2
Content-Type: application/json

### Get Posts
GET {{host}}/feed
Content-Type: application/json

### Like Post
POST {{host}}/posts/2/like
Content-Type: application/json

### Comment on Post
POST {{host}}/posts/2/comments
Content-Type: application/json

{
    "content": "This is a comment on the post!"
}

### Like Post
POST {{host}}/posts/2/like
Content-Type: application/json

### Unlike Post
POST {{host}}/posts/2/unlike
Content-Type: application/json

### Get Trending Posts
GET {{host}}/trending
Content-Type: application/json

### Upload Meme
POST {{host}}/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="meme_image"; filename="meme.jpeg"
Content-Type: image/jpeg

< ./meme.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="caption"

Check out this meme!
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="category"

funny
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="visibility"

public
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="tags"

funny
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="tags"

meme
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Delete Post
DELETE {{host}}/delete_post/2

### Get user profile
GET {{host}}/profile

### Update user profile
PATCH {{host}}/profile/update
Content-Type: application/json

{
    "display_name": "John Doe",
    "bio": "This is my new bio!"
}

### Logout
POST {{host}}/api/logout

### Try after logout
GET {{host}}/api/me